### PR TITLE
Add permissions/cooldown manager to api

### PR DESCRIPTION
**Pull request by Tschrock**
I've added some helper objects to the API to make managing cool-downs(timeouts), permissions, and the current user data easier as well as plugins to go with them. Also added a check to filter out duplicate chat messages as well as ignore the chat backlog that gets sent on connect.

Example of new api usage: https://github.com/Tschrock/PicartoChatBot/blob/experimental/plugins/challenge_message.pbot.js

### CODE REVIEW

**Comment by Wolvan** [comment]
I'll start merging this in manually now, let's see how it goes

**Comment by Wolvan** [comment]
I tried my best to merge it in commit 2d5b2c7c45b459c8b462e6e81ed287582097b4cc but I'd like if you could check over it yourself once more, @Tschrock. Not sure how good I managed to implement the split channel-based permissions.

Would that be OK with you?

**Comment by Tschrock** [comment]
May want to split timeouts between channels as well, other than that it looks good!

**Comment by Wolvan** [comment]
Alright, did that, @Tschrock. Mind explaining to me how the permissions and timeout system works? Didn't really manage to make heads or tails out of it

**Comment by Tschrock** [comment]
@Wolvan See https://gist.github.com/Tschrock/c6a0f79fa1e0fb511217
I think I got it all down, feel free to ask questions.

**Pull request closed without merging**
